theme = "rose_pine"

[editor]
true-color = true
color-modes = true
cursorline = true
bufferline = "always" # Enable tab bar at the top
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz" # Make the jump alphabet focus on home row keys

[editor.soft-wrap]
enable = true
wrap-indicator = "»"

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# File explorer configuration
[editor.file-picker]
hidden = false
parents = false

[keys.normal]

# its scary...
esc = ["collapse_selection", "keep_primary_selection"]

# vim bindings
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
# 0 = "goto_line_start"
# "$" = "goto_line_end"
# "^" = "goto_first_nonwhitespace"
# G = "goto_file_end"

# g = { d = ["goto_definition", "collapse_selection"]}

"ret" = "goto_word" # picker
tab = ":buffer-next"

