# [[language]]
# name = "markdown"
# auto-format = true
# # formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "todotxt"
language-servers = ["markdown-oxide"]
scope = "text.todotxt"
file-types = [{ glob = "todo.txt" }, { glob = "todo.md" }, "todotxt"]
formatter = { command = "sort" }
auto-format = true
